"""gdrive service installation logic."""

import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict

from gdrive import config


def _get_bin_path(name: str) -> str:
    """Find absolute path of a binary."""
    path = shutil.which(name)
    if not path:
        raise RuntimeError(f"Binary '{name}' not found in PATH.")
    return str(Path(path).absolute())


def validate_prerequisites() -> None:
    """Check if all prerequisites are met."""
    if sys.platform != "linux":
        raise RuntimeError("Service installation is only supported on Linux.")

    # Check binaries
    _get_bin_path("uv")
    _get_bin_path(config.get_gog_bin())

    # Check GOG_ACCOUNT
    config.get_account()

    # Check systemctl --user
    try:
        subprocess.run(
            ["systemctl", "--user", "status"],
            capture_output=True, check=True
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        raise RuntimeError("systemctl --user is not available or not working correctly.")


def _generate_env_file(path: Path) -> None:
    """Generate environment file for the service."""
    path.parent.mkdir(parents=True, exist_ok=True)
    
    env_vars: Dict[str, str] = {
        "GOG_ACCOUNT": config.get_account(),
        "OS_GDRIVE_DB_PATH": str(Path(config.get_db_path()).absolute()),
        "OS_GDRIVE_GOG_BIN": config.get_gog_bin(),
        "OS_GDRIVE_LOG_PATH": str(Path(config.get_log_path()).absolute()),
    }
    
    exclude = ",".join(config.get_exclude_folders())
    if exclude:
        env_vars["OS_GDRIVE_EXCLUDE_FOLDERS"] = exclude

    # Add PATH to ensure binaries are found
    env_vars["PATH"] = os.environ.get("PATH", "")

    with open(path, "w") as f:
        f.write("# Generated by gdrive service install\n")
        for key, val in env_vars.items():
            f.write(f"{key}={val}\n")


def install() -> None:
    """Install and activate gdrive systemd service and timer."""
    validate_prerequisites()

    user_config_dir = Path.home() / ".config"
    service_dir = user_config_dir / "systemd" / "user"
    env_dir = user_config_dir / "gdrive"
    
    service_dir.mkdir(parents=True, exist_ok=True)
    env_dir.mkdir(parents=True, exist_ok=True)

    env_file = env_dir / "env"
    service_file = service_dir / "gdrive.service"
    timer_file = service_dir / "gdrive.timer"

    scripts_dir = Path(__file__).parent.parent.absolute()

    # 0. Sync dependencies
    print("Syncing dependencies via uv...")
    subprocess.run([_get_bin_path("uv"), "sync"], cwd=scripts_dir, check=True)

    # 1. Generate env file
    _generate_env_file(env_file)
    print(f"Generated environment file: {env_file}")

    # 2. Generate gdrive.service
    service_content = f"""[Unit]
Description=Google Drive reindex
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
WorkingDirectory={scripts_dir}
ExecStart={_get_bin_path("uv")} run python -m gdrive.cli reindex
EnvironmentFile={env_file}

[Install]
WantedBy=default.target
"""
    with open(service_file, "w") as f:
        f.write(service_content)
    print(f"Generated service file: {service_file}")

    # 3. Generate gdrive.timer
    timer_content = """[Unit]
Description=Run gdrive reindex every 12 hours

[Timer]
OnBootSec=5min
OnUnitActiveSec=12h
Persistent=true

[Install]
WantedBy=timers.target
"""
    with open(timer_file, "w") as f:
        f.write(timer_content)
    print(f"Generated timer file: {timer_file}")

    # 4. Reload and enable
    print("Activating service...")
    subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
    subprocess.run(["systemctl", "--user", "enable", "--now", "gdrive.timer"], check=True)

    print("\nService installed and activated successfully!")
    print("Next run scheduled in 12 hours.")
    print("You can check status with: systemctl --user status gdrive.timer")
    print("Manual run: systemctl --user start gdrive.service")
